// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermercadoMDDII.Models;

#nullable disable

namespace SupermercadoMDDII.Migrations
{
    [DbContext(typeof(SupermercadoContext))]
    [Migration("20240220040117_m2")]
    partial class m2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupermercadoMDDII.Models.AsistenciaModel", b =>
                {
                    b.Property<int>("Idasistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idasistencia"));

                    b.Property<int>("Idusuario")
                        .HasColumnType("int");

                    b.Property<double>("horasExtra")
                        .HasColumnType("float");

                    b.Property<DateTime>("ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("salida")
                        .HasColumnType("datetime2");

                    b.HasKey("Idasistencia");

                    b.HasIndex("Idusuario");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcategoria"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idcategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ClienteModel", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("puntosRecompensa")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Idcliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ConfiguracionModel", b =>
                {
                    b.Property<int>("Idconfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idconfiguracion"));

                    b.Property<string>("propiedad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("recurso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("valor")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Idconfiguracion");

                    b.ToTable("Configuracion ");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.DetalleVentaModel", b =>
                {
                    b.Property<int>("IddetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddetalleVenta"));

                    b.Property<int>("Idproducto")
                        .HasColumnType("int");

                    b.Property<int>("Idventa")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("IddetalleVenta");

                    b.HasIndex("Idproducto");

                    b.HasIndex("Idventa");

                    b.ToTable("DetalleVenta ");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.EstadoPedidoModel", b =>
                {
                    b.Property<int>("IdestadoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdestadoPedido"));

                    b.Property<int>("Idpedido")
                        .HasColumnType("int");

                    b.Property<string>("calificiacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdestadoPedido");

                    b.HasIndex("Idpedido");

                    b.ToTable("EstadoPedido");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.NegocioModel", b =>
                {
                    b.Property<int>("Idnegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnegocio"));

                    b.Property<string>("correo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("direccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("porcentajeImpuesto")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ruc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idnegocio");

                    b.ToTable("Negocio");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.PedidoModel", b =>
                {
                    b.Property<int>("Idpedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpedido"));

                    b.Property<int>("Idproducto")
                        .HasColumnType("int");

                    b.Property<int>("Idproveedor")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("precioU")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Idpedido");

                    b.HasIndex("Idproducto");

                    b.HasIndex("Idproveedor");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ProductoModel", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproducto"));

                    b.Property<int>("Idcategoria")
                        .HasColumnType("int");

                    b.Property<int>("Idproveedor")
                        .HasColumnType("int");

                    b.Property<string>("codigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Idproducto");

                    b.HasIndex("Idcategoria");

                    b.HasIndex("Idproveedor");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ProveedorModel", b =>
                {
                    b.Property<int>("Idproveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproveedor"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Idproveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("esActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("sueldo")
                        .IsRequired()
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Idusuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.VentaModel", b =>
                {
                    b.Property<int>("Idventa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idventa"));

                    b.Property<int>("Idcliente")
                        .HasColumnType("int");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("fechaRegistro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("impuestoTotal")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("subTotal")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Idventa");

                    b.HasIndex("Idcliente");

                    b.HasIndex("Idusuario");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.AsistenciaModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.UsuarioModel", "Usuarios")
                        .WithMany("Asistencias")
                        .HasForeignKey("Idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.DetalleVentaModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.ProductoModel", "Productos")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("Idproducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermercadoMDDII.Models.VentaModel", "Ventas")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("Idventa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.EstadoPedidoModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.PedidoModel", "Pedidos")
                        .WithMany()
                        .HasForeignKey("Idpedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.PedidoModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.ProductoModel", "Productos")
                        .WithMany("Pedidos")
                        .HasForeignKey("Idproducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermercadoMDDII.Models.ProveedorModel", "Proveedors")
                        .WithMany("Pedidos")
                        .HasForeignKey("Idproveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Proveedors");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ProductoModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.CategoriaModel", "Categorias")
                        .WithMany("Productos")
                        .HasForeignKey("Idcategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermercadoMDDII.Models.ProveedorModel", "Proveedors")
                        .WithMany("Productos")
                        .HasForeignKey("Idproveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Proveedors");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.VentaModel", b =>
                {
                    b.HasOne("SupermercadoMDDII.Models.ClienteModel", "Clientes")
                        .WithMany("Ventas")
                        .HasForeignKey("Idcliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermercadoMDDII.Models.UsuarioModel", "Usuarios")
                        .WithMany("Ventas")
                        .HasForeignKey("Idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.CategoriaModel", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ClienteModel", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ProductoModel", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.ProveedorModel", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.UsuarioModel", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SupermercadoMDDII.Models.VentaModel", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
